config/routes.rb
QuickByte::Application.routes.draw do
  resources :group_meals

  resources :meals
  resources :users

  get "home/index"

  devise_for :users
  
  match '/group_meals/getUserGroups', :controller => 'group_meals', :action => 'getUserGroups'
  match '/group_meals/proposeNewTimes', :controller => 'group_meals', :action => 'proposeNewTimes'
  match '/group_meals/setTimes', :controller => 'group_meals', :action => 'setTimes'
  match '/group_meals/joinGroup', :controller => 'group_meals', :action => 'joinGroup'
  match '/meals/eatHere', :controller => 'meals', :action => 'eatHere'
  match '/businesses/autoComp', :controller => 'businesses', :action => 'autoComp'
  match '/group_meals/newMessage', :controller => 'group_meals', :action => 'newMessage'
  match 'auth/:provider/callback', to: 'sessions#create'
  match 'auth/failure', to: redirect('/')
  match 'signout', to: 'sessions#destroy', as: 'signout'

  resources :reviews
  resources :businesses

  root :to => "home#index"

end

app/models/business.rb
class Business < ActiveRecord::Base
  has_and_belongs_to_many :categories
  has_and_belongs_to_many :schools
  attr_accessible :business_id, :city, :full_address, :name, :open, :photo_url, :review_count, :stars, :state, :url, :latitude, :longitude
end

app/models/businesses_school.rb
class BusinessesSchool < ActiveRecord::Base
  attr_accessible :business_id, :school_id
end

app/models/businesses_schools.rb
class BusinessesSchools < ActiveRecord::Base
  attr_accessible :business_id, :school_id
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_and_belongs_to_many :businesses
  attr_accessible :name
  
end

app/models/group_meal.rb
class GroupMeal < ActiveRecord::Base
  has_and_belongs_to_many :users
  attr_accessible :meal, :proposed_end_time, :proposed_start_time, :set_end_time, :set_start_time
end

app/models/group_meal_message.rb
class GroupMealMessage < ActiveRecord::Base
  attr_accessible :group_meal_id, :message_id
end

app/models/meal.rb
class Meal < ActiveRecord::Base
  attr_accessible :end_time, :host, :location, :start_time, :privacy_level, :user_tokens
  before_validation :location_exists
  attr_reader :user_tokens
  
  validate :date_must_be_in_future
  validate :start_greater_end
  
  def start_greater_end
    if start_time > end_time
      errors.add :base, "Start time should Be Less Than End Time!"
    end
  end
  
  def date_must_be_in_future
    if start_time < DateTime.now
      errors.add(:start_time, "Start Time Must Be In Future")
    end
  end
  
  def location_exists
    if location == " "
    	errors.add(:location, "Please Select A Location")
    end
  end
  
  
end

app/models/message.rb
class Message < ActiveRecord::Base
  attr_accessible :author, :text, :group_meal_id
end

app/models/private.rb
class Private < ActiveRecord::Base
  attr_accessible :meal_id, :user_id
end

app/models/review.rb
class Review < ActiveRecord::Base
  attr_accessible :business_id, :date, :review_id, :stars, :text, :user_id
end

app/models/school.rb
class School < ActiveRecord::Base
  has_and_belongs_to_many :businesses
  attr_accessible :name
end

app/models/user.rb
class User < ActiveRecord::Base
  has_and_belongs_to_many :group_meals
  attr_accessible :college
  
  # Pulls info from facebook and updates user attributes
  def self.from_omniauth(auth)
    where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
		user.provider = auth.provider
		user.uid = auth.uid
		user.name = auth.info.name
		user.oauth_token = auth.credentials.token
		user.oauth_expires_at = Time.at(auth.credentials.expires_at)
		user.email=auth.info.email
		user.image=auth.info.image
		user.location=auth.info.location
		user.facebook_url=auth.info.urls.Facebook
		puts("education here")
		@school=""
		puts(auth.extra.raw_info)
		puts(auth.info)
		puts(auth.extra)
		if(auth.extra.raw_info.education !=nil)
			auth.extra.raw_info.education.each do |e|
				if e.type="College"
					@school=e.school.name
				end
			end
			user.college=@school
		else
			@school="University of Pennsylvania"
			user.college=@school
		end
		user.save!
  	end
  end
end

app/controllers/businesses_controller.rb
class BusinessesController < ApplicationController

  

  before_filter :authenticate
 
  def authenticate
    redirect_to "/" unless current_user!=nil
  end
  # GET /businesses
  # GET /businesses.json
  def index
    @businesses = Business.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @businesses }
    end
  end

  def autoComp
  	@business=Business.find_by_name(params[:search])
    redirect_to @business
  end

  # GET /businesses/1
  # GET /businesses/1.json
  def show
    @business = Business.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @business }
    end
  end

  # GET /businesses/new
  # GET /businesses/new.json
  def new
    @business = Business.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @business }
    end
  end

  # GET /businesses/1/edit
  def edit
    @business = Business.find(params[:id])
  end

  # POST /businesses
  # POST /businesses.json
  def create
    @business = Business.new(params[:business])

    respond_to do |format|
      if @business.save
        format.html { redirect_to @business, notice: 'Business was successfully created.' }
        format.json { render json: @business, status: :created, location: @business }
      else
        format.html { render action: "new" }
        format.json { render json: @business.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /businesses/1
  # PUT /businesses/1.json
  def update
    @business = Business.find(params[:id])

    respond_to do |format|
      if @business.update_attributes(params[:business])
        format.html { redirect_to @business, notice: 'Business was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @business.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /businesses/1
  # DELETE /businesses/1.json
  def destroy
    @business = Business.find(params[:id])
    @business.destroy

    respond_to do |format|
      format.html { redirect_to businesses_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/business_helper.rb
module BusinessHelper
end

app/helpers/businesses_helper.rb
module BusinessesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/meals_helper.rb
module MealsHelper
end

app/helpers/message_helper.rb
module MessageHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/businesses/_form.html.erb
<%= form_for(@business) do |f| %>
  <% if @business.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@business.errors.count, "error") %> prohibited this business from being saved:</h2>

      <ul>
      <% @business.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :business_id %><br />
    <%= f.text_field :business_id %>
  </div>
  <div class="field">
    <%= f.label :full_address %><br />
    <%= f.text_field :full_address %>
  </div>
  <div class="field">
    <%= f.label :open %><br />
    <%= f.check_box :open %>
  </div>
  <div class="field">
    <%= f.label :photo_url %><br />
    <%= f.text_field :photo_url %>
  </div>
  <div class="field">
    <%= f.label :city %><br />
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :review_count %><br />
    <%= f.number_field :review_count %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :state %><br />
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :stars %><br />
    <%= f.number_field :stars %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/businesses/edit.html.erb
<h1>Editing business</h1>

<%= render 'form' %>

<%= link_to 'Show', @business %> |
<%= link_to 'Back', businesses_path %>

app/views/businesses/index.html.erb
<h1>Listing businesses</h1>
<a href="#" class="button">Default Button</a>
<table>
  <tr>
    <th>Business</th>
    <th>Full address</th>
    <th>Open</th>
    <th>Photo url</th>
    <th>City</th>
    <th>Review count</th>
    <th>Name</th>
    <th>Url</th>
    <th>State</th>
    <th>Stars</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @businesses.each do |business| %>
  <tr>
    <td><%= business.business_id %></td>
    <td><%= business.full_address %></td>
    <td><%= business.open %></td>
    <td><%= business.photo_url %></td>
    <td><%= business.city %></td>
    <td><%= business.review_count %></td>
    <td><%= business.name %></td>
    <td><%= business.url %></td>
    <td><%= business.state %></td>
    <td><%= business.stars %></td>
    <td><%= link_to 'Show', business %></td>
    <td><%= link_to 'Edit', edit_business_path(business) %></td>
    <td><%= link_to 'Destroy', business, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Business', new_business_path %>

app/views/businesses/new.html.erb
<h1>New business</h1>

<%= render 'form' %>

<%= link_to 'Back', businesses_path %>

app/views/businesses/show.html.erb
<div class="row" >
	<div class="large-6 columns">
		<div class="panel">
			<p id="notice"><%= notice %></p>
			<div style="float:right">
			  <img src="<%= @business.photo_url %>"><%= button_to 'Eat Here', {:controller => "meals", :action => "eatHere", :business => @business.id},  :method => "post" , :class =>"button" %>
			</div> 
			<p>
			<h3><%= @business.name %></h3>
			</p>
			<p>
			<%= @business.full_address %>
			</p>	
			<p>
			  <b>Url:</b>
			  <a href="<%= @business.url %>" target="_blank"> <%= @business.url %> <a/>
			</p>
			
			<p>
			  <p>Stars:
					<% if @business.stars == 1  %> 
					  <%= image_tag "1star.jpg" %>
					<% end %>
					<% if @business.stars == 2  %> 
					  <%= image_tag "2star.jpg" %>
					<% end %>
					<% if @business.stars == 3  %> 
					  <%= image_tag "3star.jpg" %>
					<% end %>
					<% if @business.stars == 4  %> 
					  <%= image_tag "4star.jpg" %>
					<% end %>
					<% if @business.stars == 5  %> 
					  <%= image_tag "5star.jpg" %>  
					<% end %>
					 </p>	
		</div>
		<%= button_to 'Back', meals_path, :method => "get", :class =>"button"  %>
	</div>
	<div class="large-6 columns">
		<h3><u> Reviews </u>:<%= @business.review_count %></h3>
			<% Review.order("date DESC").find_all_by_business_id(@business.business_id).each do |e|%> 
				<div class="panel">
					<p><b><%= e.date %></b></p>
					<p>Stars:
					<% if e.stars == 1  %> 
					  <%= image_tag "1star.jpg" %>
					<% end %>
					<% if e.stars == 2  %> 
					  <%= image_tag "2star.jpg" %>
					<% end %>
					<% if e.stars == 3  %> 
					  <%= image_tag "3star.jpg" %>
					<% end %>
					<% if e.stars == 4  %> 
					  <%= image_tag "4star.jpg" %>
					<% end %>
					<% if e.stars == 5  %> 
					  <%= image_tag "5star.jpg" %>  
					<% end %>
					 </p>
					<br />
					<p><%= e.text %></p>
					<br />
				</div>
			<% end %>
	</div>
</div>	