config/routes.rb
QuickByte::Application.routes.draw do
  resources :group_meals

  resources :meals
  resources :users

  get "home/index"

  devise_for :users
  
  match '/group_meals/getUserGroups', :controller => 'group_meals', :action => 'getUserGroups'
  match '/group_meals/proposeNewTimes', :controller => 'group_meals', :action => 'proposeNewTimes'
  match '/group_meals/setTimes', :controller => 'group_meals', :action => 'setTimes'
  match '/group_meals/joinGroup', :controller => 'group_meals', :action => 'joinGroup'
  match '/meals/eatHere', :controller => 'meals', :action => 'eatHere'
  match '/businesses/autoComp', :controller => 'businesses', :action => 'autoComp'
  match '/group_meals/newMessage', :controller => 'group_meals', :action => 'newMessage'
  match 'auth/:provider/callback', to: 'sessions#create'
  match 'auth/failure', to: redirect('/')
  match 'signout', to: 'sessions#destroy', as: 'signout'

  resources :reviews
  resources :businesses

  root :to => "home#index"

end

app/models/group_meal.rb
class GroupMeal < ActiveRecord::Base
  has_and_belongs_to_many :users
  attr_accessible :meal, :proposed_end_time, :proposed_start_time, :set_end_time, :set_start_time
end

app/controllers/group_meals_controller.rb
class GroupMealsController < ApplicationController
  # GET /group_meals
  # GET /group_meals.json
  def index
    @group_meals = GroupMeal.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @group_meals }
    end
  end

  #Creates a new message for the group_meal and alerts all members
  def newMessage

    @message =Message.new
    @message.author=current_user.id
    @message.text=params[:text]
    @message.group_meal_id= params[:group_meal_id]
    @message.save
    
    query = "SELECT user_id FROM group_meals_participants where group_meal_id = " + params[:group_meal_id]
    
    GroupMealsParticipant.connection.select_values(query).each do |u|
    	if(u!=current_user.id)
    		u=User.find(u)
    		u.alert=true
    		u.alert_location=params[:group_meal_id]
    		u.save
    	end
    end
    
    redirect_to group_meal_path(GroupMeal.find(params[:group_meal_id]).id)
  end

  # GET /group_meals/1
  # GET /group_meals/1.json
  def show
    @group_meal = GroupMeal.find(params[:id])
    if(current_user.alert==true)
   		current_user.alert=false
		current_user.save
	end
	if(current_user.alert_location= @group_meal.id)
		current_user.alert_location=nil
		current_user.save
	end
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @group_meal }
    end
  end

  #Gets group meals for current User
  def getUserGroups
  	@group_meals=GroupMealsParticipant.find_all_by_user_id(current_user.id)
  	if(current_user.alert)
  		current_user.alert=false
  		current_user.save
  	end
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @group_meal }
    end
  end

  #Joins user to selected group meal
  def joinGroup
  	query = "SELECT user_id FROM group_meals_participants where group_meal_id = " + GroupMeal.find_by_meal(params[:meal]).id.to_s
    
    GroupMealsParticipant.connection.select_values(query).each do |u|
    	if(u!=current_user.id)
    		u=User.find(u)
    		u.alert=true
    		u.alert_location=GroupMeal.find_by_meal(params[:meal]).id.to_s
    		u.save
    	end
  	end
      @groupMealParticipant= GroupMealsParticipant.new
      @groupMealParticipant.user_id=current_user.id
      @groupMealParticipant.group_meal_id= GroupMeal.find_by_meal(params[:meal]).id
      @groupMealParticipant.save     
      redirect_to(GroupMeal.find_by_meal(params[:meal]))
  end

  # GET /group_meals/new
  # GET /group_meals/new.json
  def new
    @group_meal = GroupMeal.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @group_meal }
    end
  end

  # GET /group_meals/1/edit
  def edit
    @group_meal = GroupMeal.find(params[:id])
  end

  # POST /group_meals
  # POST /group_meals.json
  def create
    @group_meal = GroupMeal.new(params[:group_meal])

    respond_to do |format|
      if @group_meal.save
        format.html { redirect_to @group_meal, notice: 'Group meal was successfully created.' }
        format.json { render json: @group_meal, status: :created, location: @group_meal }
      else
        format.html { render action: "new" }
        format.json { render json: @group_meal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /group_meals/1
  # PUT /group_meals/1.json
  # Updates proposed or set time and alerts users
  def update
    @group_meal = GroupMeal.find(params[:id])
    respond_to do |format|
      if @group_meal.update_attributes(params[:group_meal])
         @meal= Meal.find(@group_meal.meal)
         
        if params[:group_meal]["proposed_start_time(2i)"] !=nil
        	startDay= params[:group_meal]["proposed_start_time(3i)"].to_i
         	startHour= params[:group_meal]["proposed_start_time(4i)"].to_i + 4
         	
         	if startHour > 24
          	  startHour=startHour % 24
           	  startDay+=1
            end
    	 
    	 	endDay= params[:group_meal]["proposed_end_time(3i)"].to_i
         	endHour= params[:group_meal]["proposed_end_time(4i)"].to_i + 4
         	
         	if endHour>24
          	  endHour=@endHour % 24
              endDay+=1
         	end
         	
        	@meal.start_time= DateTime.new(params[:group_meal]["proposed_start_time(1i)"].to_i, 
                        params[:group_meal]["proposed_start_time(2i)"].to_i,
                        startDay,
                        startHour,
                        params[:group_meal]["proposed_start_time(5i)"].to_i)
            @meal.end_time= DateTime.new(params[:group_meal]["proposed_end_time(1i)"].to_i, 
                        params[:group_meal]["proposed_end_time(2i)"].to_i,
                        endDay,
                        endHour,
                        params[:group_meal]["proposed_end_time(5i)"].to_i)
        	@meal.save
        end
        
        if params[:group_meal]["set_start_time(2i)"] !=nil
        
        	startDay= params[:group_meal]["set_start_time(3i)"].to_i
         	startHour= params[:group_meal]["set_start_time(4i)"].to_i + 4
         	
         	if startHour > 24
          	  startHour=startHour % 24
           	  startDay+=1
            end
    	 
    	 	endDay= params[:group_meal]["set_end_time(3i)"].to_i
         	endHour= params[:group_meal]["set_end_time(4i)"].to_i + 4
         	
         	if endHour>24
          	  endHour=endHour % 24
              endDay+=1
         	end
        	@meal.start_time= DateTime.new(params[:group_meal]["set_start_time(1i)"].to_i, 
                        params[:group_meal]["set_start_time(2i)"].to_i,
                        startDay,
                        startHour,
                        params[:group_meal]["set_start_time(5i)"].to_i)
            @meal.end_time= DateTime.new(params[:group_meal]["set_end_time(1i)"].to_i, 
                        params[:group_meal]["set_end_time(2i)"].to_i,
                        endDay,
                        endHour,
                        params[:group_meal]["set_end_time(5i)"].to_i)
        	@meal.save
        end
        
        query = "SELECT user_id FROM group_meals_participants where group_meal_id = " + @group_meal.id.to_s
    
    	GroupMealsParticipant.connection.select_values(query).each do |u|
    	if(u!=current_user.id)
    		u=User.find(u)
    		u.alert=true
    		u.alert_location=@group_meal.id
    		u.save
    	end
    end
        
        
        format.html { redirect_to @group_meal, notice: 'Group meal was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @group_meal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /group_meals/1
  # DELETE /group_meals/1.json
  def destroy
    @group_meal = GroupMeal.find(params[:id])
    @group_meal.destroy

    respond_to do |format|
      format.html { redirect_to group_meals_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/group_meals_helper.rb
module GroupMealsHelper
end

app/views/group_meals/_form.html.erb
<%= simple_form_for(@group_meal) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :meal %>
    <%= f.datetime_select :proposed_start_time, :ampm => true, :start_year => 2013, :order => [:month, :day, :year] %>
    <%= f.datetime_select :proposed_end_time, :ampm => true, :start_year => 2013, :order => [:month, :day, :year] %>
    <%= f.datetime_select :set_start_time, :ampm => true, :start_year => 2013, :order => [:month, :day, :year] %>
    <%= f.datetime_select :set_start_time, :ampm => true, :start_year => 2013, :order => [:month, :day, :year] %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/group_meals/edit.html.erb
<h1>Editing group_meal</h1>

<%= render 'form' %>

<%= link_to 'Show', @group_meal %> |
<%= link_to 'Back', group_meals_path %>

app/views/group_meals/getUserGroups.html.erb
<%= button_to 'Back', meals_path, :method => 'get', :class =>"button" %>
<% if @group_meals == [] %>
  <h1> You Are Not A Part Of Any Group Meals Yet! </h1>
<% end %>
<% @group_meals.each do |group_meal| %>
  <% gm=GroupMeal.find(group_meal.group_meal_id) %>
  <% if gm.proposed_start_time > DateTime.now %>
	  <div style="font-size:40px;font-style:italic;display:inline"><%= Business.find(Meal.find(gm.meal).location).name %></div>
		<% if current_user.id == Meal.find(gm.meal).host %>
		  <span class="round alert label">Hosting!</span>
		<% end %>
	  <div class="panel" >
		<div class="row">
			<div class="large-3 columns">
				<img src= "<%= Business.find_by_id(Meal.find(gm.meal).location).photo_url %>" >
				<h5>Host: <em style="display:block"><%= User.find(Meal.find(gm.meal).host).name %></em></h5>
				<h5>Participants:</h5>
					<% GroupMealsParticipant.find_all_by_group_meal_id(gm.id).each do |g| %>
					  <% if g.user_id != Meal.find(gm.meal).host %>
						<em style="display:inline"><%= User.find(g.user_id).name %></em>
					  <% end %>
					<% end %>
			</div>
			<div class="large-8 columns">
				<table>
				  <tr>
					<th>Proposed start time</th>
					<td> <%= gm.proposed_start_time.strftime("%m/%d at %I:%M%p") %></td>
				  </tr>
				  <tr>
					<th>Proposed end time</th>
					<td><%= gm.proposed_end_time.strftime("%m/%d at %I:%M%p") %></td>
				  </tr>
				  <tr>
					<th>Set start time</th>
					<% if gm.set_start_time. !=nil %>
						<td><b><%= gm.set_start_time.strftime("%m/%d at %I:%M%p") %></b></td>
					<% else %>
						<td>TBD!</td>
					<% end %>
				  </tr>
				  <tr>
					<th>Set end time</th>
					<% if gm.set_end_time. !=nil %>
						<td><b><%= gm.set_end_time.strftime("%m/%d at %I:%M%p") %></b></td>
					<% else %>
						<td>TBD!</td>
					<% end %>
				  </tr>
				</table>
				<%= button_to 'Go To Group Meal', {:controller => "group_meals", :action => "show", :id =>gm.id},  :method => "get" , :class =>"button" %>
			</div>
			<div class="large-1 column" >
				<% if current_user.alert_location== gm.id %>
					<%= image_tag "notification.gif"  %>
				<% end %>
			</div>
		</div>
	  </div>
	<% end %>
<% end %>

app/views/group_meals/index.html.erb
<h1>Listing group_meals</h1>

<table>
  <tr>
    <th>Meal</th>
    <th>Proposed start time</th>
    <th>Proposed end time</th>
    <th>Set start time</th>
    <th>Set end time</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @group_meals.each do |group_meal| %>
  <tr>
    <td><%= group_meal.meal %></td>
    <td><%= group_meal.proposed_start_time %></td>
    <td><%= group_meal.proposed_end_time %></td>
    <td><%= group_meal.set_start_time %></td>
    <td><%= group_meal.set_end_time %></td>
    <td><%= link_to 'Show', group_meal %></td>
    <td><%= link_to 'Edit', edit_group_meal_path(group_meal) %></td>
    <td><%= link_to 'Destroy', group_meal, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Group meal', new_group_meal_path %>

app/views/group_meals/new.html.erb
<h1>New group_meal</h1>

<%= render 'form' %>

<%= link_to 'Back', group_meals_path %>

app/views/group_meals/show.html.erb
<p id="notice"><%= notice %></p>
<div style="font-size:40px;font-style:italic;display:inline"><%= Business.find(Meal.find(@group_meal.meal).location).name %></div>
<% if current_user.id == Meal.find(@group_meal.meal).host %>
	  <span class="round alert label">Hosting!</span>
<% end %>
<div class="panel" >
	<div class="row">
		<div class="large-3 columns">
			<img src= "<%= Business.find_by_id(Meal.find(@group_meal.meal).location).photo_url %>" >
			<h5>Host: <em style="display:block"><%= link_to User.find(Meal.find(@group_meal.meal).host).name, User.find(Meal.find(@group_meal.meal).host) %></em></h5>
			<h5>Participants:</h5>
				<% GroupMealsParticipant.find_all_by_group_meal_id(@group_meal.id).each do |g| %>
				  <% if g.user_id != Meal.find(@group_meal.meal).host %>
				    <em style="display:inline"><%= link_to User.find(g.user_id).name, User.find(g.user_id) %></em>	<br />
				  <% end %>
				<% end %>
		</div>
		<div class="large-9 columns">
			<table>
			  <tr>
				<th>Proposed start time</th>
				<th>Proposed end time</th>
				<th>Set start time</th>
				<th>Set end time</th>
				<th></th>
				<th></th>
				<th></th>
			  </tr>
			  <tr>
			  	<td> <%= @group_meal.proposed_start_time.strftime("%m/%d at %I:%M%p") %></td>
			  	<td><%= @group_meal.proposed_end_time.strftime("%m/%d at %I:%M%p") %></td>
			  	
			  	<% if @group_meal.set_start_time. !=nil %>
			  		<td><%= @group_meal.set_start_time.strftime("%m/%d at %I:%M%p") %></td>
			  		<td><%= @group_meal.set_end_time.strftime("%m/%d at %I:%M%p") %></td>
			  	<% else %>
			  		<td>TBD!</td>
			  		<td>TBD!</td>
			  	<% end %>
			  </tr>
			</table>
			<div class="row" >
				<% if @group_meal.set_start_time. ==nil %>
					<div class="large-5 large-offset-1 columns">
						<button class="button" id="buttonProp">Propose New Times </button>
					</div>
					<div class="large-6 columns">
						<% if current_user == User.find(Meal.find(@group_meal.meal).host) %>
							<button class="button" id="buttonSet" >Set Times </button>					
						<% end %>
					</div>
				<% else %>
					<div class="large-5 large-offset-1 columns">
						<button  type="button" class="button" id="buttonProp" disabled>Propose New Times </button>
					</div>
					<div class="large-6 columns">
						<% if current_user == User.find(Meal.find(@group_meal.meal).host) %>
							<button type="button" class="button" id="buttonSet" disabled>Set Times </button>					
						<% end %>
					</div>
				
				<% end %>
			</div>
			<div class="row">
				<%= simple_form_for(@group_meal,:html => {:id => "updateProp", :class =>"custom" }) do |f| %>
					<div class="form-inputs">
					  <div class="large-6 columns">
						Proposed Start Time:<%= f.datetime_select :proposed_start_time, :ampm => true, :start_year => 2013, :order => [:month, :day, :year], :minute_step => 15  %>
    				  </div>
    				  <div class="large-6 columns">	
    					Proposed End Time:<%= f.datetime_select :proposed_end_time, :ampm => true, :start_year => 2013, :order => [:month, :day, :year], :minute_step => 15  %>
				      </div>
				    </div> 	
					  <div class="form-actions">
						<%= f.button :submit , :class => "button" %>
					  </div>
				<% end %>
			</div>
			<div class="row">
				<%= simple_form_for(@group_meal,:html => {:id => "updateSet" , :class =>"custom"}) do |f| %>
					<div class="form-inputs">
					<div class="large-6 columns">
						Set Start Time:<%= f.datetime_select :set_start_time, :ampm => true, :start_year => 2013, :order => [:month, :day, :year], :minute_step => 15  %>
    				</div>
    				<div class="large-6 columns">	
    					Set End Time:<%= f.datetime_select :set_end_time, :ampm => true, :start_year => 2013, :order => [:month, :day, :year], :minute_step => 15  %>
					  </div>
					  </div>
					  <div class="form-actions">
						<%= f.button :submit , :class => "button" %>
					  </div>
				<% end %>
			  </div>
			</div>
		</div>
	</div>
</div>
<div class="panel">
  <h3>Message Board</h3>
  <div id="messages" style="background-color:white;height:160px;overflow:scroll" >
	  <% Message.order('created_at ASC').find_all_by_group_meal_id(@group_meal.id).each do |m| %>
		<%= User.find(m.author).name %> (<%= m.created_at.strftime("%m/%d at %I:%M%p") %>): <%= m.text %> <br />
	  <% end %>  
  </div>
  <div class="row">
  	  <%= form_tag(:controller => "group_meals", :action => "newMessage", :method => "post", :group_meal_id => @group_meal.id) do  %>
  	    <div class="large-9 columns">
	      <%= text_area_tag :text %>
	    </div>
	    <div class="large-3 columns">
	      <%= submit_tag "Send Message" , :class => "button" %>
	    </div>
	  <% end %>
	</div>
</div>
<%= button_to 'Back', meals_path, :method => 'get', :class =>"button" %>