config/routes.rb
QuickByte::Application.routes.draw do
  resources :group_meals

  resources :meals
  resources :users

  get "home/index"

  devise_for :users
  
  match '/group_meals/getUserGroups', :controller => 'group_meals', :action => 'getUserGroups'
  match '/group_meals/proposeNewTimes', :controller => 'group_meals', :action => 'proposeNewTimes'
  match '/group_meals/setTimes', :controller => 'group_meals', :action => 'setTimes'
  match '/group_meals/joinGroup', :controller => 'group_meals', :action => 'joinGroup'
  match '/meals/eatHere', :controller => 'meals', :action => 'eatHere'
  match '/businesses/autoComp', :controller => 'businesses', :action => 'autoComp'
  match '/group_meals/newMessage', :controller => 'group_meals', :action => 'newMessage'
  match 'auth/:provider/callback', to: 'sessions#create'
  match 'auth/failure', to: redirect('/')
  match 'signout', to: 'sessions#destroy', as: 'signout'

  resources :reviews
  resources :businesses

  root :to => "home#index"

end

app/models/business.rb
class Business < ActiveRecord::Base
  has_and_belongs_to_many :categories
  has_and_belongs_to_many :schools
  attr_accessible :business_id, :city, :full_address, :name, :open, :photo_url, :review_count, :stars, :state, :url, :latitude, :longitude
end

app/models/businesses_school.rb
class BusinessesSchool < ActiveRecord::Base
  attr_accessible :business_id, :school_id
end

app/models/businesses_schools.rb
class BusinessesSchools < ActiveRecord::Base
  attr_accessible :business_id, :school_id
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_and_belongs_to_many :businesses
  attr_accessible :name
  
end

app/models/group_meal.rb
class GroupMeal < ActiveRecord::Base
  has_and_belongs_to_many :users
  attr_accessible :meal, :proposed_end_time, :proposed_start_time, :set_end_time, :set_start_time
end

app/models/group_meal_message.rb
class GroupMealMessage < ActiveRecord::Base
  attr_accessible :group_meal_id, :message_id
end

app/models/meal.rb
class Meal < ActiveRecord::Base
  attr_accessible :end_time, :host, :location, :start_time, :privacy_level, :user_tokens
  before_validation :location_exists
  attr_reader :user_tokens
  
  validate :date_must_be_in_future
  validate :start_greater_end
  
  def start_greater_end
    if start_time > end_time
      errors.add :base, "Start time should Be Less Than End Time!"
    end
  end
  
  def date_must_be_in_future
    if start_time < DateTime.now
      errors.add(:start_time, "Start Time Must Be In Future")
    end
  end
  
  def location_exists
    if location == " "
    	errors.add(:location, "Please Select A Location")
    end
  end
  
  
end

app/models/message.rb
class Message < ActiveRecord::Base
  attr_accessible :author, :text, :group_meal_id
end

app/models/private.rb
class Private < ActiveRecord::Base
  attr_accessible :meal_id, :user_id
end

app/models/review.rb
class Review < ActiveRecord::Base
  attr_accessible :business_id, :date, :review_id, :stars, :text, :user_id
end

app/models/school.rb
class School < ActiveRecord::Base
  has_and_belongs_to_many :businesses
  attr_accessible :name
end

app/models/user.rb
class User < ActiveRecord::Base
  has_and_belongs_to_many :group_meals
  attr_accessible :college
  
  # Pulls info from facebook and updates user attributes
  def self.from_omniauth(auth)
    where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
		user.provider = auth.provider
		user.uid = auth.uid
		user.name = auth.info.name
		user.oauth_token = auth.credentials.token
		user.oauth_expires_at = Time.at(auth.credentials.expires_at)
		user.email=auth.info.email
		user.image=auth.info.image
		user.location=auth.info.location
		user.facebook_url=auth.info.urls.Facebook
		puts("education here")
		@school=""
		puts(auth.extra.raw_info)
		puts(auth.info)
		puts(auth.extra)
		if(auth.extra.raw_info.education !=nil)
			auth.extra.raw_info.education.each do |e|
				if e.type="College"
					@school=e.school.name
				end
			end
			user.college=@school
		else
			@school="University of Pennsylvania"
			user.college=@school
		end
		user.save!
  	end
  end
end

app/controllers/meals_controller.rb
class MealsController < ApplicationController
  
  before_filter :authenticate
 
  def authenticate
    redirect_to "/" unless current_user!=nil
  end
  
  # GET /meals
  # GET /meals.json
  # Returns viewable meals to user that are > DateTime
  def index

    @meals = Meal.where("privacy_level =? AND start_time > ?", "public", DateTime.now).order("start_time")
    @privateMeals= Private.where("user_id = ?" ,current_user.id)

    if(@privateMeals !=nil)
		@privateMeals.each do |p|
			puts("here wtf")
			@priv= Meal.where("id= ? AND privacy_level =? AND start_time > ?" , p.meal_id,"private", DateTime.now)
			@meals += @priv 
		end
    end

    if(@meals.size >1)
      @meals.sort! { |a,b| a.start_time <=> b.start_time }
    end
    
    @user= current_user
    @part = GroupMealsParticipant.find_all_by_user_id(@user.id)
	@part.each do |f|
		if @businesses == nil
			@businesses = Business.where("id = ?", Meal.find(GroupMeal.find(f.group_meal_id).meal).location)
		else
			@businesses += Business.where("id = ?", Meal.find(GroupMeal.find(f.group_meal_id).meal).location)
		end
	end
	
	@x = Hash.new(0)	
	if @businesses !=nil
		@businesses.each do |b|
			@x[b] += 1
		end
		@ordered= @x.sort_by { |k,v| v }.reverse
	end
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @meals }
    end
  end
  
  #Starts New Meal
  def eatHere
  	@meal= Meal.new
	@meal.location=(params[:business])
  	render 'new'
  end
  
  # GET /meals/1
  # GET /meals/1.json
  def show
    @meal = Meal.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @meal }
    end
  end

  # GET /meals/new
  # GET /meals/new.json
  def new
    @meal = Meal.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @meal }
    end
  end

  # GET /meals/1/edit
  def edit
    @meal = Meal.find(params[:id])
  end
  
  # POST /meals
  # POST /meals.json
  # Creates New Meal and group_meal
  def create
  
    if((params[:meal][:location]).to_s.numeric?)
      bId=params[:meal][:location]
    else
      bId=Business.find_by_name(params[:meal][:location]).id
    end
    @meal = Meal.new(params[:meal])
    @meal.location=bId
    @meal.host=current_user.id
    respond_to do |format|
    if @meal.save
      if (params[:private] !=nil)
		  @priArray= (params[:private]).split(", ")
		  @priArray.each do |p|

			  @private= Private.new
			  @private.meal_id=@meal.id
			  @private.user_id= p
			  @private.save
		  end
		  			  
		  @private2=Private.new
		  @private2.meal_id=@meal.id
		  @private2.user_id= current_user.id
		  @private2.save
	  end
	  
	  @group_meal = GroupMeal.new
	  @group_meal.meal=@meal.id
	  @group_meal.proposed_start_time= @meal.start_time
	  @group_meal.proposed_end_time= @meal.end_time
	  @group_meal.set_start_time= nil
	  @group_meal.set_start_time= nil
	  @group_meal.save
	  @groupMealParticipant= GroupMealsParticipant.new
	  @groupMealParticipant.user_id=current_user.id
	  @groupMealParticipant.group_meal_id= @group_meal.id
	  @groupMealParticipant.save    
      format.html { redirect_to :controller => 'group_meals', :action => 'show', :id => @group_meal.id, notice: 'Meal was successfully created.' }
      format.json { render json: @meal, status: :created, location: @meal }
      else
        format.html { render action: "new" }
        format.json { render json: @meal.errors, status: :unprocessable_entity }
      end
    end
    
  end

  # PUT /meals/1
  # PUT /meals/1.json
  def update
    @meal = Meal.find(params[:id])

    respond_to do |format|
      if @meal.update_attributes(params[:meal])
        format.html { redirect_to meals_url, notice: 'Meal was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @meal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meals/1
  # DELETE /meals/1.json
  def destroy
    @meal = Meal.find(params[:id])
    @meal.destroy

    respond_to do |format|
      format.html { redirect_to meals_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/business_helper.rb
module BusinessHelper
end

app/helpers/businesses_helper.rb
module BusinessesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/meals_helper.rb
module MealsHelper
end

app/helpers/message_helper.rb
module MessageHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/meals/_form.html.erb
<script>	
	function showDiv(chosen){
	  if(chosen == "Private")
	    document.getElementById("privacy").style.display = "block"
	  else
	  	document.getElementById("privacy").style.display = "none"
	}
	
</script>

<%= simple_form_for @meal, :html => { :class =>"custom", :id=> "myForm"} do |f| %>
  <% if @meal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@meal.errors.count, "error") %> prohibited this meal from being saved:</h2>

      <ul>
      <% @meal.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field" style="width:50%"> 
    <b>Location</b>
    <% if @meal.location == nil%>
        <%= f.text_field :location, data: {autocomplete_source: Business.connection.select_values(query)},:placeholder => "Enter A Location", :class => 'code_input' %>
    <% else %>
        <%= f.text_field :location, data: {autocomplete_source: Business.connection.select_values(query)}, :readonly => "true" %>
  	 <% end %>
  </div>
  <div class="field" style="width:25%;float:right;margin-right:30%">
    <b>End Time</b><br />
    <%= f.datetime_select :end_time, :ampm => true, :start_year => 2013, :order => [:month, :day, :year], :minute_step => 15 %>
  </div>
  <div style="float:right;margin-right:8%">
  	<b>to</b>
  </div>
  <div class="field"  style="width:25%">
    <b>Start Time</b><br />
    <%= f.datetime_select :start_time, :ampm => true, :start_year => 2013, :order => [:month, :day, :year], :minute_step => 15  %>
  </div>
  <div class="field" style="width:30%">
    <b>Privacy Level <b><br />
    <%= f.select :privacy_level, options_for_select([["Public", "public"], ["Private", "private"]]), {} , :onchange => 'showDiv(this.options[this.selectedIndex].innerHTML)' %>
  </div>
  
  <div id="privacy" style="display:none"  >
    <h5> Type users who can see this </h5>
	<%= text_field_tag 'private', nil %>
  </div><br /><br />
  <div class="actions">
    <%= f.submit 'Create Meal', {:id => 'button_id', :class => 'button'}%>
  </div>
<% end %>

app/views/meals/edit.html.erb
<h1>Editing meal</h1>

<%= render 'form' %>

<%= link_to 'Show', @meal %> |
<%= link_to 'Back', meals_path %>

app/views/meals/index.html.erb
<div class="panel">
	<div class="style:float-left">
		<%= button_to "New Meal", new_meal_path,:method => :get,class:"button" %>
	<h1 style="text-align:center">MealFeed</h1>	
	<div>
		<% @meals.each do |m| %>
		<div class="row">
			<div class="large-9 columns">
				<table style="width:600px;text-align:center">
				  <tr>
					<td><img src="<%= Business.find_by_id(m.location).photo_url %>"></td>
					<th>Start Time</th>
					<th>End Time</th>
					<th>Host</th>
				  </tr>
				  <tr>
					<td width="30%" onmouseover="this.style.cursor='pointer';" onclick="window.location.href = '<%= url_for(:controller => 'businesses', :action => 'show', :id=>m.location) %>' "><h5><u><%= Business.find_by_id(m.location).name %><u></h5></td>
					<td width="20%"><%= m.start_time.strftime("%m/%d at %I:%M%p")%></td>
					<td width="20%"><%= m.end_time.strftime("%I:%M%p")%></td>
					<td width="20%"><% if current_user.id == m.host %> <span class="round alert label">You!</span> <% else %><%= link_to User.find(m.host).name, User.find(m.host)  %> <% end %></td>
				  </tr>
				</table>
			</div>
			<div class="large-3 columns">
				<% if GroupMeal.find_by_meal(m.id) != nil  %>
					<% if (m.host == current_user.id || GroupMealsParticipant.find_by_user_id_and_group_meal_id(current_user.id,GroupMeal.find_by_meal(m.id).id)!=nil)%>
						<%= link_to 'See Group Meal', group_meal_path(GroupMeal.find_by_meal(m.id)), :class =>"button" %>
					<% else %>
							<%= button_to 'Join', {:controller => "group_meals", :action => "joinGroup", :meal =>m.id},  :method => "post" , :class =>"button" %>
					<% end %>
					
					<% if GroupMeal.find_by_meal(m.id).set_start_time != nil %>
						<span class="round alert label">Final Time Set!</span>
					<% end %>
				<% else %>
					<%= button_to 'Join', {:controller => "group_meals", :action => "joinGroup", :meal =>m.id},  :method => "post" , :class =>"button" %>
				<% end %>
			</div>
		</div>
		<% end %>
	</div>
</div>

app/views/meals/new.html.erb
<div class="panel">
	<div class="row">
	    <div class="large-6 columns">
			<h1>Create a New Meal!</h1>
			<%= render 'form' %>
			<%= link_to 'Back', meals_path %>
		</div>
		<div class="large-6 columns">
		  <h3 style="text-align:left;margin-top:20%"> To make a new meal <br /> <br /> 
		  Simply pick a location <br /> <br /> 
		  A start and end time <br /> <br /> 
		  And if you want this meal to be seen publicly <br /> <br /> 
		  Or only by certain people!</h3>
		</div>
	</div>
</div>

app/views/meals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Host:</b>
  <%= @meal.host %>
</p>

<p>
  <b>Start time:</b>
  <%= @meal.start_time %>
</p>

<p>
  <b>End time:</b>
  <%= @meal.end_time %>
</p>

<p>
  <b>Location:</b>
  <%= @meal.location %>
</p>


<%= link_to 'Edit', edit_meal_path(@meal) %> |
<%= link_to 'Back', meals_path %>